// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: OraProtoBuf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_BEGIN  Op = 0
	Op_COMMIT Op = 1
	Op_INSERT Op = 2
	Op_UPDATE Op = 3
	Op_DELETE Op = 4
	Op_DDL    Op = 5
	Op_CHKPT  Op = 6
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "BEGIN",
		1: "COMMIT",
		2: "INSERT",
		3: "UPDATE",
		4: "DELETE",
		5: "DDL",
		6: "CHKPT",
	}
	Op_value = map[string]int32{
		"BEGIN":  0,
		"COMMIT": 1,
		"INSERT": 2,
		"UPDATE": 3,
		"DELETE": 4,
		"DDL":    5,
		"CHKPT":  6,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_OraProtoBuf_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_OraProtoBuf_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{0}
}

type ColumnType int32

const (
	ColumnType_UNKNOWN                 ColumnType = 0
	ColumnType_VARCHAR2                ColumnType = 1
	ColumnType_NUMBER                  ColumnType = 2
	ColumnType_LONG                    ColumnType = 3
	ColumnType_DATE                    ColumnType = 4
	ColumnType_RAW                     ColumnType = 5
	ColumnType_LONG_RAW                ColumnType = 6
	ColumnType_CHAR                    ColumnType = 7
	ColumnType_BINARY_FLOAT            ColumnType = 8
	ColumnType_BINARY_DOUBLE           ColumnType = 9
	ColumnType_CLOB                    ColumnType = 10
	ColumnType_BLOB                    ColumnType = 11
	ColumnType_TIMESTAMP               ColumnType = 12
	ColumnType_TIMESTAMP_WITH_TZ       ColumnType = 13
	ColumnType_INTERVAL_YEAR_TO_MONTH  ColumnType = 14
	ColumnType_INTERVAL_DAY_TO_SECOND  ColumnType = 15
	ColumnType_UROWID                  ColumnType = 16
	ColumnType_TIMESTAMP_WITH_LOCAL_TZ ColumnType = 17
)

// Enum value maps for ColumnType.
var (
	ColumnType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "VARCHAR2",
		2:  "NUMBER",
		3:  "LONG",
		4:  "DATE",
		5:  "RAW",
		6:  "LONG_RAW",
		7:  "CHAR",
		8:  "BINARY_FLOAT",
		9:  "BINARY_DOUBLE",
		10: "CLOB",
		11: "BLOB",
		12: "TIMESTAMP",
		13: "TIMESTAMP_WITH_TZ",
		14: "INTERVAL_YEAR_TO_MONTH",
		15: "INTERVAL_DAY_TO_SECOND",
		16: "UROWID",
		17: "TIMESTAMP_WITH_LOCAL_TZ",
	}
	ColumnType_value = map[string]int32{
		"UNKNOWN":                 0,
		"VARCHAR2":                1,
		"NUMBER":                  2,
		"LONG":                    3,
		"DATE":                    4,
		"RAW":                     5,
		"LONG_RAW":                6,
		"CHAR":                    7,
		"BINARY_FLOAT":            8,
		"BINARY_DOUBLE":           9,
		"CLOB":                    10,
		"BLOB":                    11,
		"TIMESTAMP":               12,
		"TIMESTAMP_WITH_TZ":       13,
		"INTERVAL_YEAR_TO_MONTH":  14,
		"INTERVAL_DAY_TO_SECOND":  15,
		"UROWID":                  16,
		"TIMESTAMP_WITH_LOCAL_TZ": 17,
	}
)

func (x ColumnType) Enum() *ColumnType {
	p := new(ColumnType)
	*p = x
	return p
}

func (x ColumnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnType) Descriptor() protoreflect.EnumDescriptor {
	return file_OraProtoBuf_proto_enumTypes[1].Descriptor()
}

func (ColumnType) Type() protoreflect.EnumType {
	return &file_OraProtoBuf_proto_enumTypes[1]
}

func (x ColumnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnType.Descriptor instead.
func (ColumnType) EnumDescriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{1}
}

type RequestCode int32

const (
	RequestCode_INFO     RequestCode = 0
	RequestCode_START    RequestCode = 1
	RequestCode_CONTINUE RequestCode = 2
	RequestCode_CONFIRM  RequestCode = 3
)

// Enum value maps for RequestCode.
var (
	RequestCode_name = map[int32]string{
		0: "INFO",
		1: "START",
		2: "CONTINUE",
		3: "CONFIRM",
	}
	RequestCode_value = map[string]int32{
		"INFO":     0,
		"START":    1,
		"CONTINUE": 2,
		"CONFIRM":  3,
	}
)

func (x RequestCode) Enum() *RequestCode {
	p := new(RequestCode)
	*p = x
	return p
}

func (x RequestCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCode) Descriptor() protoreflect.EnumDescriptor {
	return file_OraProtoBuf_proto_enumTypes[2].Descriptor()
}

func (RequestCode) Type() protoreflect.EnumType {
	return &file_OraProtoBuf_proto_enumTypes[2]
}

func (x RequestCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestCode.Descriptor instead.
func (RequestCode) EnumDescriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{2}
}

type ResponseCode int32

const (
	ResponseCode_READY            ResponseCode = 0
	ResponseCode_FAILED_START     ResponseCode = 1
	ResponseCode_STARTING         ResponseCode = 2
	ResponseCode_ALREADY_STARTED  ResponseCode = 3
	ResponseCode_REPLICATE        ResponseCode = 4
	ResponseCode_PAYLOAD          ResponseCode = 5
	ResponseCode_INVALID_DATABASE ResponseCode = 6
	ResponseCode_INVALID_COMMAND  ResponseCode = 7
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "READY",
		1: "FAILED_START",
		2: "STARTING",
		3: "ALREADY_STARTED",
		4: "REPLICATE",
		5: "PAYLOAD",
		6: "INVALID_DATABASE",
		7: "INVALID_COMMAND",
	}
	ResponseCode_value = map[string]int32{
		"READY":            0,
		"FAILED_START":     1,
		"STARTING":         2,
		"ALREADY_STARTED":  3,
		"REPLICATE":        4,
		"PAYLOAD":          5,
		"INVALID_DATABASE": 6,
		"INVALID_COMMAND":  7,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_OraProtoBuf_proto_enumTypes[3].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_OraProtoBuf_proto_enumTypes[3]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{3}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Datum:
	//
	//	*Value_ValueInt
	//	*Value_ValueFloat
	//	*Value_ValueDouble
	//	*Value_ValueString
	//	*Value_ValueBytes
	Datum         isValue_Datum `protobuf_oneof:"datum"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_OraProtoBuf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Value) GetDatum() isValue_Datum {
	if x != nil {
		return x.Datum
	}
	return nil
}

func (x *Value) GetValueInt() int64 {
	if x != nil {
		if x, ok := x.Datum.(*Value_ValueInt); ok {
			return x.ValueInt
		}
	}
	return 0
}

func (x *Value) GetValueFloat() float32 {
	if x != nil {
		if x, ok := x.Datum.(*Value_ValueFloat); ok {
			return x.ValueFloat
		}
	}
	return 0
}

func (x *Value) GetValueDouble() float64 {
	if x != nil {
		if x, ok := x.Datum.(*Value_ValueDouble); ok {
			return x.ValueDouble
		}
	}
	return 0
}

func (x *Value) GetValueString() string {
	if x != nil {
		if x, ok := x.Datum.(*Value_ValueString); ok {
			return x.ValueString
		}
	}
	return ""
}

func (x *Value) GetValueBytes() []byte {
	if x != nil {
		if x, ok := x.Datum.(*Value_ValueBytes); ok {
			return x.ValueBytes
		}
	}
	return nil
}

type isValue_Datum interface {
	isValue_Datum()
}

type Value_ValueInt struct {
	ValueInt int64 `protobuf:"varint,2,opt,name=value_int,json=valueInt,proto3,oneof"`
}

type Value_ValueFloat struct {
	ValueFloat float32 `protobuf:"fixed32,3,opt,name=value_float,json=valueFloat,proto3,oneof"`
}

type Value_ValueDouble struct {
	ValueDouble float64 `protobuf:"fixed64,4,opt,name=value_double,json=valueDouble,proto3,oneof"`
}

type Value_ValueString struct {
	ValueString string `protobuf:"bytes,5,opt,name=value_string,json=valueString,proto3,oneof"`
}

type Value_ValueBytes struct {
	ValueBytes []byte `protobuf:"bytes,6,opt,name=value_bytes,json=valueBytes,proto3,oneof"`
}

func (*Value_ValueInt) isValue_Datum() {}

func (*Value_ValueFloat) isValue_Datum() {}

func (*Value_ValueDouble) isValue_Datum() {}

func (*Value_ValueString) isValue_Datum() {}

func (*Value_ValueBytes) isValue_Datum() {}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          ColumnType             `protobuf:"varint,2,opt,name=type,proto3,enum=OpenLogReplicator.pb.ColumnType" json:"type,omitempty"`
	Length        int32                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Precision     int32                  `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         int32                  `protobuf:"varint,5,opt,name=scale,proto3" json:"scale,omitempty"`
	Nullable      bool                   `protobuf:"varint,6,opt,name=nullable,proto3" json:"nullable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_OraProtoBuf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{1}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() ColumnType {
	if x != nil {
		return x.Type
	}
	return ColumnType_UNKNOWN
}

func (x *Column) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Column) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Column) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Column) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Owner string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Obj   uint32                 `protobuf:"varint,3,opt,name=obj,proto3" json:"obj,omitempty"`
	// Types that are valid to be assigned to TmVal:
	//
	//	*Schema_Tm
	//	*Schema_Tms
	TmVal         isSchema_TmVal `protobuf_oneof:"tm_val"`
	Column        []*Column      `protobuf:"bytes,6,rep,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_OraProtoBuf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{2}
}

func (x *Schema) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Schema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schema) GetObj() uint32 {
	if x != nil {
		return x.Obj
	}
	return 0
}

func (x *Schema) GetTmVal() isSchema_TmVal {
	if x != nil {
		return x.TmVal
	}
	return nil
}

func (x *Schema) GetTm() uint64 {
	if x != nil {
		if x, ok := x.TmVal.(*Schema_Tm); ok {
			return x.Tm
		}
	}
	return 0
}

func (x *Schema) GetTms() string {
	if x != nil {
		if x, ok := x.TmVal.(*Schema_Tms); ok {
			return x.Tms
		}
	}
	return ""
}

func (x *Schema) GetColumn() []*Column {
	if x != nil {
		return x.Column
	}
	return nil
}

type isSchema_TmVal interface {
	isSchema_TmVal()
}

type Schema_Tm struct {
	Tm uint64 `protobuf:"varint,4,opt,name=tm,proto3,oneof"`
}

type Schema_Tms struct {
	Tms string `protobuf:"bytes,5,opt,name=tms,proto3,oneof"`
}

func (*Schema_Tm) isSchema_TmVal() {}

func (*Schema_Tms) isSchema_TmVal() {}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Op                     `protobuf:"varint,1,opt,name=op,proto3,enum=OpenLogReplicator.pb.Op" json:"op,omitempty"`
	Schema        *Schema                `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	Rid           string                 `protobuf:"bytes,3,opt,name=rid,proto3" json:"rid,omitempty"`
	Before        []*Value               `protobuf:"bytes,4,rep,name=before,proto3" json:"before,omitempty"`
	After         []*Value               `protobuf:"bytes,5,rep,name=after,proto3" json:"after,omitempty"`
	Ddl           string                 `protobuf:"bytes,6,opt,name=ddl,proto3" json:"ddl,omitempty"`
	Seq           uint32                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Offset        uint64                 `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Redo          bool                   `protobuf:"varint,9,opt,name=redo,proto3" json:"redo,omitempty"`
	Num           uint64                 `protobuf:"varint,10,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_OraProtoBuf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{3}
}

func (x *Payload) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_BEGIN
}

func (x *Payload) GetSchema() *Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Payload) GetRid() string {
	if x != nil {
		return x.Rid
	}
	return ""
}

func (x *Payload) GetBefore() []*Value {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Payload) GetAfter() []*Value {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *Payload) GetDdl() string {
	if x != nil {
		return x.Ddl
	}
	return ""
}

func (x *Payload) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Payload) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Payload) GetRedo() bool {
	if x != nil {
		return x.Redo
	}
	return false
}

func (x *Payload) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mask          string                 `protobuf:"bytes,1,opt,name=mask,proto3" json:"mask,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRequest) Reset() {
	*x = SchemaRequest{}
	mi := &file_OraProtoBuf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRequest) ProtoMessage() {}

func (x *SchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRequest.ProtoReflect.Descriptor instead.
func (*SchemaRequest) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{4}
}

func (x *SchemaRequest) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *SchemaRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type RedoRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Code         RequestCode            `protobuf:"varint,1,opt,name=code,proto3,enum=OpenLogReplicator.pb.RequestCode" json:"code,omitempty"`
	DatabaseName string                 `protobuf:"bytes,2,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	// Types that are valid to be assigned to TmVal:
	//
	//	*RedoRequest_Scn
	//	*RedoRequest_Tms
	//	*RedoRequest_TmRel
	TmVal         isRedoRequest_TmVal `protobuf_oneof:"tm_val"`
	Seq           *uint64             `protobuf:"varint,6,opt,name=seq,proto3,oneof" json:"seq,omitempty"`
	Schema        []*SchemaRequest    `protobuf:"bytes,7,rep,name=schema,proto3" json:"schema,omitempty"`
	CScn          *uint64             `protobuf:"varint,8,opt,name=c_scn,json=cScn,proto3,oneof" json:"c_scn,omitempty"`
	CIdx          *uint64             `protobuf:"varint,9,opt,name=c_idx,json=cIdx,proto3,oneof" json:"c_idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedoRequest) Reset() {
	*x = RedoRequest{}
	mi := &file_OraProtoBuf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedoRequest) ProtoMessage() {}

func (x *RedoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedoRequest.ProtoReflect.Descriptor instead.
func (*RedoRequest) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{5}
}

func (x *RedoRequest) GetCode() RequestCode {
	if x != nil {
		return x.Code
	}
	return RequestCode_INFO
}

func (x *RedoRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *RedoRequest) GetTmVal() isRedoRequest_TmVal {
	if x != nil {
		return x.TmVal
	}
	return nil
}

func (x *RedoRequest) GetScn() uint64 {
	if x != nil {
		if x, ok := x.TmVal.(*RedoRequest_Scn); ok {
			return x.Scn
		}
	}
	return 0
}

func (x *RedoRequest) GetTms() string {
	if x != nil {
		if x, ok := x.TmVal.(*RedoRequest_Tms); ok {
			return x.Tms
		}
	}
	return ""
}

func (x *RedoRequest) GetTmRel() int64 {
	if x != nil {
		if x, ok := x.TmVal.(*RedoRequest_TmRel); ok {
			return x.TmRel
		}
	}
	return 0
}

func (x *RedoRequest) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *RedoRequest) GetSchema() []*SchemaRequest {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *RedoRequest) GetCScn() uint64 {
	if x != nil && x.CScn != nil {
		return *x.CScn
	}
	return 0
}

func (x *RedoRequest) GetCIdx() uint64 {
	if x != nil && x.CIdx != nil {
		return *x.CIdx
	}
	return 0
}

type isRedoRequest_TmVal interface {
	isRedoRequest_TmVal()
}

type RedoRequest_Scn struct {
	Scn uint64 `protobuf:"varint,3,opt,name=scn,proto3,oneof"`
}

type RedoRequest_Tms struct {
	Tms string `protobuf:"bytes,4,opt,name=tms,proto3,oneof"`
}

type RedoRequest_TmRel struct {
	TmRel int64 `protobuf:"varint,5,opt,name=tm_rel,json=tmRel,proto3,oneof"`
}

func (*RedoRequest_Scn) isRedoRequest_TmVal() {}

func (*RedoRequest_Tms) isRedoRequest_TmVal() {}

func (*RedoRequest_TmRel) isRedoRequest_TmVal() {}

type RedoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ResponseCode           `protobuf:"varint,1,opt,name=code,proto3,enum=OpenLogReplicator.pb.ResponseCode" json:"code,omitempty"`
	// Types that are valid to be assigned to ScnVal:
	//
	//	*RedoResponse_Scn
	//	*RedoResponse_Scns
	ScnVal isRedoResponse_ScnVal `protobuf_oneof:"scn_val"`
	// Types that are valid to be assigned to TmVal:
	//
	//	*RedoResponse_Tm
	//	*RedoResponse_Tms
	TmVal isRedoResponse_TmVal `protobuf_oneof:"tm_val"`
	// Types that are valid to be assigned to XidVal:
	//
	//	*RedoResponse_Xid
	//	*RedoResponse_Xidn
	XidVal        isRedoResponse_XidVal `protobuf_oneof:"xid_val"`
	Db            string                `protobuf:"bytes,8,opt,name=db,proto3" json:"db,omitempty"`
	Payload       []*Payload            `protobuf:"bytes,9,rep,name=payload,proto3" json:"payload,omitempty"`
	CScn          uint64                `protobuf:"varint,10,opt,name=c_scn,json=cScn,proto3" json:"c_scn,omitempty"`
	CIdx          uint64                `protobuf:"varint,11,opt,name=c_idx,json=cIdx,proto3" json:"c_idx,omitempty"`
	Attributes    map[string]string     `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedoResponse) Reset() {
	*x = RedoResponse{}
	mi := &file_OraProtoBuf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedoResponse) ProtoMessage() {}

func (x *RedoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OraProtoBuf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedoResponse.ProtoReflect.Descriptor instead.
func (*RedoResponse) Descriptor() ([]byte, []int) {
	return file_OraProtoBuf_proto_rawDescGZIP(), []int{6}
}

func (x *RedoResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_READY
}

func (x *RedoResponse) GetScnVal() isRedoResponse_ScnVal {
	if x != nil {
		return x.ScnVal
	}
	return nil
}

func (x *RedoResponse) GetScn() uint64 {
	if x != nil {
		if x, ok := x.ScnVal.(*RedoResponse_Scn); ok {
			return x.Scn
		}
	}
	return 0
}

func (x *RedoResponse) GetScns() string {
	if x != nil {
		if x, ok := x.ScnVal.(*RedoResponse_Scns); ok {
			return x.Scns
		}
	}
	return ""
}

func (x *RedoResponse) GetTmVal() isRedoResponse_TmVal {
	if x != nil {
		return x.TmVal
	}
	return nil
}

func (x *RedoResponse) GetTm() uint64 {
	if x != nil {
		if x, ok := x.TmVal.(*RedoResponse_Tm); ok {
			return x.Tm
		}
	}
	return 0
}

func (x *RedoResponse) GetTms() string {
	if x != nil {
		if x, ok := x.TmVal.(*RedoResponse_Tms); ok {
			return x.Tms
		}
	}
	return ""
}

func (x *RedoResponse) GetXidVal() isRedoResponse_XidVal {
	if x != nil {
		return x.XidVal
	}
	return nil
}

func (x *RedoResponse) GetXid() string {
	if x != nil {
		if x, ok := x.XidVal.(*RedoResponse_Xid); ok {
			return x.Xid
		}
	}
	return ""
}

func (x *RedoResponse) GetXidn() uint64 {
	if x != nil {
		if x, ok := x.XidVal.(*RedoResponse_Xidn); ok {
			return x.Xidn
		}
	}
	return 0
}

func (x *RedoResponse) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *RedoResponse) GetPayload() []*Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RedoResponse) GetCScn() uint64 {
	if x != nil {
		return x.CScn
	}
	return 0
}

func (x *RedoResponse) GetCIdx() uint64 {
	if x != nil {
		return x.CIdx
	}
	return 0
}

func (x *RedoResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type isRedoResponse_ScnVal interface {
	isRedoResponse_ScnVal()
}

type RedoResponse_Scn struct {
	Scn uint64 `protobuf:"varint,2,opt,name=scn,proto3,oneof"`
}

type RedoResponse_Scns struct {
	Scns string `protobuf:"bytes,3,opt,name=scns,proto3,oneof"`
}

func (*RedoResponse_Scn) isRedoResponse_ScnVal() {}

func (*RedoResponse_Scns) isRedoResponse_ScnVal() {}

type isRedoResponse_TmVal interface {
	isRedoResponse_TmVal()
}

type RedoResponse_Tm struct {
	Tm uint64 `protobuf:"varint,4,opt,name=tm,proto3,oneof"`
}

type RedoResponse_Tms struct {
	Tms string `protobuf:"bytes,5,opt,name=tms,proto3,oneof"`
}

func (*RedoResponse_Tm) isRedoResponse_TmVal() {}

func (*RedoResponse_Tms) isRedoResponse_TmVal() {}

type isRedoResponse_XidVal interface {
	isRedoResponse_XidVal()
}

type RedoResponse_Xid struct {
	Xid string `protobuf:"bytes,6,opt,name=xid,proto3,oneof"`
}

type RedoResponse_Xidn struct {
	Xidn uint64 `protobuf:"varint,7,opt,name=xidn,proto3,oneof"`
}

func (*RedoResponse_Xid) isRedoResponse_XidVal() {}

func (*RedoResponse_Xidn) isRedoResponse_XidVal() {}

var File_OraProtoBuf_proto protoreflect.FileDescriptor

const file_OraProtoBuf_proto_rawDesc = "" +
	"\n" +
	"\x11OraProtoBuf.proto\x12\x14OpenLogReplicator.pb\"\xd3\x01\n" +
	"\x05Value\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\tvalue_int\x18\x02 \x01(\x03H\x00R\bvalueInt\x12!\n" +
	"\vvalue_float\x18\x03 \x01(\x02H\x00R\n" +
	"valueFloat\x12#\n" +
	"\fvalue_double\x18\x04 \x01(\x01H\x00R\vvalueDouble\x12#\n" +
	"\fvalue_string\x18\x05 \x01(\tH\x00R\vvalueString\x12!\n" +
	"\vvalue_bytes\x18\x06 \x01(\fH\x00R\n" +
	"valueBytesB\a\n" +
	"\x05datum\"\xba\x01\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .OpenLogReplicator.pb.ColumnTypeR\x04type\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x05R\x06length\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x05 \x01(\x05R\x05scale\x12\x1a\n" +
	"\bnullable\x18\x06 \x01(\bR\bnullable\"\xaa\x01\n" +
	"\x06Schema\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03obj\x18\x03 \x01(\rR\x03obj\x12\x10\n" +
	"\x02tm\x18\x04 \x01(\x04H\x00R\x02tm\x12\x12\n" +
	"\x03tms\x18\x05 \x01(\tH\x00R\x03tms\x124\n" +
	"\x06column\x18\x06 \x03(\v2\x1c.OpenLogReplicator.pb.ColumnR\x06columnB\b\n" +
	"\x06tm_val\"\xc5\x02\n" +
	"\aPayload\x12(\n" +
	"\x02op\x18\x01 \x01(\x0e2\x18.OpenLogReplicator.pb.OpR\x02op\x124\n" +
	"\x06schema\x18\x02 \x01(\v2\x1c.OpenLogReplicator.pb.SchemaR\x06schema\x12\x10\n" +
	"\x03rid\x18\x03 \x01(\tR\x03rid\x123\n" +
	"\x06before\x18\x04 \x03(\v2\x1b.OpenLogReplicator.pb.ValueR\x06before\x121\n" +
	"\x05after\x18\x05 \x03(\v2\x1b.OpenLogReplicator.pb.ValueR\x05after\x12\x10\n" +
	"\x03ddl\x18\x06 \x01(\tR\x03ddl\x12\x10\n" +
	"\x03seq\x18\a \x01(\rR\x03seq\x12\x16\n" +
	"\x06offset\x18\b \x01(\x04R\x06offset\x12\x12\n" +
	"\x04redo\x18\t \x01(\bR\x04redo\x12\x10\n" +
	"\x03num\x18\n" +
	" \x01(\x04R\x03num\";\n" +
	"\rSchemaRequest\x12\x12\n" +
	"\x04mask\x18\x01 \x01(\tR\x04mask\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"\xd8\x02\n" +
	"\vRedoRequest\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.OpenLogReplicator.pb.RequestCodeR\x04code\x12#\n" +
	"\rdatabase_name\x18\x02 \x01(\tR\fdatabaseName\x12\x12\n" +
	"\x03scn\x18\x03 \x01(\x04H\x00R\x03scn\x12\x12\n" +
	"\x03tms\x18\x04 \x01(\tH\x00R\x03tms\x12\x17\n" +
	"\x06tm_rel\x18\x05 \x01(\x03H\x00R\x05tmRel\x12\x15\n" +
	"\x03seq\x18\x06 \x01(\x04H\x01R\x03seq\x88\x01\x01\x12;\n" +
	"\x06schema\x18\a \x03(\v2#.OpenLogReplicator.pb.SchemaRequestR\x06schema\x12\x18\n" +
	"\x05c_scn\x18\b \x01(\x04H\x02R\x04cScn\x88\x01\x01\x12\x18\n" +
	"\x05c_idx\x18\t \x01(\x04H\x03R\x04cIdx\x88\x01\x01B\b\n" +
	"\x06tm_valB\x06\n" +
	"\x04_seqB\b\n" +
	"\x06_c_scnB\b\n" +
	"\x06_c_idx\"\xe6\x03\n" +
	"\fRedoResponse\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".OpenLogReplicator.pb.ResponseCodeR\x04code\x12\x12\n" +
	"\x03scn\x18\x02 \x01(\x04H\x00R\x03scn\x12\x14\n" +
	"\x04scns\x18\x03 \x01(\tH\x00R\x04scns\x12\x10\n" +
	"\x02tm\x18\x04 \x01(\x04H\x01R\x02tm\x12\x12\n" +
	"\x03tms\x18\x05 \x01(\tH\x01R\x03tms\x12\x12\n" +
	"\x03xid\x18\x06 \x01(\tH\x02R\x03xid\x12\x14\n" +
	"\x04xidn\x18\a \x01(\x04H\x02R\x04xidn\x12\x0e\n" +
	"\x02db\x18\b \x01(\tR\x02db\x127\n" +
	"\apayload\x18\t \x03(\v2\x1d.OpenLogReplicator.pb.PayloadR\apayload\x12\x13\n" +
	"\x05c_scn\x18\n" +
	" \x01(\x04R\x04cScn\x12\x13\n" +
	"\x05c_idx\x18\v \x01(\x04R\x04cIdx\x12R\n" +
	"\n" +
	"attributes\x18\f \x03(\v22.OpenLogReplicator.pb.RedoResponse.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\ascn_valB\b\n" +
	"\x06tm_valB\t\n" +
	"\axid_val*S\n" +
	"\x02Op\x12\t\n" +
	"\x05BEGIN\x10\x00\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x01\x12\n" +
	"\n" +
	"\x06INSERT\x10\x02\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\a\n" +
	"\x03DDL\x10\x05\x12\t\n" +
	"\x05CHKPT\x10\x06*\xa8\x02\n" +
	"\n" +
	"ColumnType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bVARCHAR2\x10\x01\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x02\x12\b\n" +
	"\x04LONG\x10\x03\x12\b\n" +
	"\x04DATE\x10\x04\x12\a\n" +
	"\x03RAW\x10\x05\x12\f\n" +
	"\bLONG_RAW\x10\x06\x12\b\n" +
	"\x04CHAR\x10\a\x12\x10\n" +
	"\fBINARY_FLOAT\x10\b\x12\x11\n" +
	"\rBINARY_DOUBLE\x10\t\x12\b\n" +
	"\x04CLOB\x10\n" +
	"\x12\b\n" +
	"\x04BLOB\x10\v\x12\r\n" +
	"\tTIMESTAMP\x10\f\x12\x15\n" +
	"\x11TIMESTAMP_WITH_TZ\x10\r\x12\x1a\n" +
	"\x16INTERVAL_YEAR_TO_MONTH\x10\x0e\x12\x1a\n" +
	"\x16INTERVAL_DAY_TO_SECOND\x10\x0f\x12\n" +
	"\n" +
	"\x06UROWID\x10\x10\x12\x1b\n" +
	"\x17TIMESTAMP_WITH_LOCAL_TZ\x10\x11*=\n" +
	"\vRequestCode\x12\b\n" +
	"\x04INFO\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\f\n" +
	"\bCONTINUE\x10\x02\x12\v\n" +
	"\aCONFIRM\x10\x03*\x95\x01\n" +
	"\fResponseCode\x12\t\n" +
	"\x05READY\x10\x00\x12\x10\n" +
	"\fFAILED_START\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\x13\n" +
	"\x0fALREADY_STARTED\x10\x03\x12\r\n" +
	"\tREPLICATE\x10\x04\x12\v\n" +
	"\aPAYLOAD\x10\x05\x12\x14\n" +
	"\x10INVALID_DATABASE\x10\x06\x12\x13\n" +
	"\x0fINVALID_COMMAND\x10\a2f\n" +
	"\x11OpenLogReplicator\x12Q\n" +
	"\x04Redo\x12!.OpenLogReplicator.pb.RedoRequest\x1a\".OpenLogReplicator.pb.RedoResponse(\x010\x01B,Z*github.com/null-ptr-exception/dblog-cdc/pbb\x06proto3"

var (
	file_OraProtoBuf_proto_rawDescOnce sync.Once
	file_OraProtoBuf_proto_rawDescData []byte
)

func file_OraProtoBuf_proto_rawDescGZIP() []byte {
	file_OraProtoBuf_proto_rawDescOnce.Do(func() {
		file_OraProtoBuf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_OraProtoBuf_proto_rawDesc), len(file_OraProtoBuf_proto_rawDesc)))
	})
	return file_OraProtoBuf_proto_rawDescData
}

var file_OraProtoBuf_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_OraProtoBuf_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_OraProtoBuf_proto_goTypes = []any{
	(Op)(0),               // 0: OpenLogReplicator.pb.Op
	(ColumnType)(0),       // 1: OpenLogReplicator.pb.ColumnType
	(RequestCode)(0),      // 2: OpenLogReplicator.pb.RequestCode
	(ResponseCode)(0),     // 3: OpenLogReplicator.pb.ResponseCode
	(*Value)(nil),         // 4: OpenLogReplicator.pb.Value
	(*Column)(nil),        // 5: OpenLogReplicator.pb.Column
	(*Schema)(nil),        // 6: OpenLogReplicator.pb.Schema
	(*Payload)(nil),       // 7: OpenLogReplicator.pb.Payload
	(*SchemaRequest)(nil), // 8: OpenLogReplicator.pb.SchemaRequest
	(*RedoRequest)(nil),   // 9: OpenLogReplicator.pb.RedoRequest
	(*RedoResponse)(nil),  // 10: OpenLogReplicator.pb.RedoResponse
	nil,                   // 11: OpenLogReplicator.pb.RedoResponse.AttributesEntry
}
var file_OraProtoBuf_proto_depIdxs = []int32{
	1,  // 0: OpenLogReplicator.pb.Column.type:type_name -> OpenLogReplicator.pb.ColumnType
	5,  // 1: OpenLogReplicator.pb.Schema.column:type_name -> OpenLogReplicator.pb.Column
	0,  // 2: OpenLogReplicator.pb.Payload.op:type_name -> OpenLogReplicator.pb.Op
	6,  // 3: OpenLogReplicator.pb.Payload.schema:type_name -> OpenLogReplicator.pb.Schema
	4,  // 4: OpenLogReplicator.pb.Payload.before:type_name -> OpenLogReplicator.pb.Value
	4,  // 5: OpenLogReplicator.pb.Payload.after:type_name -> OpenLogReplicator.pb.Value
	2,  // 6: OpenLogReplicator.pb.RedoRequest.code:type_name -> OpenLogReplicator.pb.RequestCode
	8,  // 7: OpenLogReplicator.pb.RedoRequest.schema:type_name -> OpenLogReplicator.pb.SchemaRequest
	3,  // 8: OpenLogReplicator.pb.RedoResponse.code:type_name -> OpenLogReplicator.pb.ResponseCode
	7,  // 9: OpenLogReplicator.pb.RedoResponse.payload:type_name -> OpenLogReplicator.pb.Payload
	11, // 10: OpenLogReplicator.pb.RedoResponse.attributes:type_name -> OpenLogReplicator.pb.RedoResponse.AttributesEntry
	9,  // 11: OpenLogReplicator.pb.OpenLogReplicator.Redo:input_type -> OpenLogReplicator.pb.RedoRequest
	10, // 12: OpenLogReplicator.pb.OpenLogReplicator.Redo:output_type -> OpenLogReplicator.pb.RedoResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_OraProtoBuf_proto_init() }
func file_OraProtoBuf_proto_init() {
	if File_OraProtoBuf_proto != nil {
		return
	}
	file_OraProtoBuf_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_ValueInt)(nil),
		(*Value_ValueFloat)(nil),
		(*Value_ValueDouble)(nil),
		(*Value_ValueString)(nil),
		(*Value_ValueBytes)(nil),
	}
	file_OraProtoBuf_proto_msgTypes[2].OneofWrappers = []any{
		(*Schema_Tm)(nil),
		(*Schema_Tms)(nil),
	}
	file_OraProtoBuf_proto_msgTypes[5].OneofWrappers = []any{
		(*RedoRequest_Scn)(nil),
		(*RedoRequest_Tms)(nil),
		(*RedoRequest_TmRel)(nil),
	}
	file_OraProtoBuf_proto_msgTypes[6].OneofWrappers = []any{
		(*RedoResponse_Scn)(nil),
		(*RedoResponse_Scns)(nil),
		(*RedoResponse_Tm)(nil),
		(*RedoResponse_Tms)(nil),
		(*RedoResponse_Xid)(nil),
		(*RedoResponse_Xidn)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_OraProtoBuf_proto_rawDesc), len(file_OraProtoBuf_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_OraProtoBuf_proto_goTypes,
		DependencyIndexes: file_OraProtoBuf_proto_depIdxs,
		EnumInfos:         file_OraProtoBuf_proto_enumTypes,
		MessageInfos:      file_OraProtoBuf_proto_msgTypes,
	}.Build()
	File_OraProtoBuf_proto = out.File
	file_OraProtoBuf_proto_goTypes = nil
	file_OraProtoBuf_proto_depIdxs = nil
}
