// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.3
// source: OraProtoBuf.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OpenLogReplicator_Redo_FullMethodName = "/OpenLogReplicator.pb.OpenLogReplicator/Redo"
)

// OpenLogReplicatorClient is the client API for OpenLogReplicator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenLogReplicatorClient interface {
	Redo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RedoRequest, RedoResponse], error)
}

type openLogReplicatorClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenLogReplicatorClient(cc grpc.ClientConnInterface) OpenLogReplicatorClient {
	return &openLogReplicatorClient{cc}
}

func (c *openLogReplicatorClient) Redo(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RedoRequest, RedoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OpenLogReplicator_ServiceDesc.Streams[0], OpenLogReplicator_Redo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RedoRequest, RedoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenLogReplicator_RedoClient = grpc.BidiStreamingClient[RedoRequest, RedoResponse]

// OpenLogReplicatorServer is the server API for OpenLogReplicator service.
// All implementations must embed UnimplementedOpenLogReplicatorServer
// for forward compatibility.
type OpenLogReplicatorServer interface {
	Redo(grpc.BidiStreamingServer[RedoRequest, RedoResponse]) error
	mustEmbedUnimplementedOpenLogReplicatorServer()
}

// UnimplementedOpenLogReplicatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOpenLogReplicatorServer struct{}

func (UnimplementedOpenLogReplicatorServer) Redo(grpc.BidiStreamingServer[RedoRequest, RedoResponse]) error {
	return status.Error(codes.Unimplemented, "method Redo not implemented")
}
func (UnimplementedOpenLogReplicatorServer) mustEmbedUnimplementedOpenLogReplicatorServer() {}
func (UnimplementedOpenLogReplicatorServer) testEmbeddedByValue()                           {}

// UnsafeOpenLogReplicatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenLogReplicatorServer will
// result in compilation errors.
type UnsafeOpenLogReplicatorServer interface {
	mustEmbedUnimplementedOpenLogReplicatorServer()
}

func RegisterOpenLogReplicatorServer(s grpc.ServiceRegistrar, srv OpenLogReplicatorServer) {
	// If the following call panics, it indicates UnimplementedOpenLogReplicatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OpenLogReplicator_ServiceDesc, srv)
}

func _OpenLogReplicator_Redo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OpenLogReplicatorServer).Redo(&grpc.GenericServerStream[RedoRequest, RedoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OpenLogReplicator_RedoServer = grpc.BidiStreamingServer[RedoRequest, RedoResponse]

// OpenLogReplicator_ServiceDesc is the grpc.ServiceDesc for OpenLogReplicator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OpenLogReplicator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OpenLogReplicator.pb.OpenLogReplicator",
	HandlerType: (*OpenLogReplicatorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Redo",
			Handler:       _OpenLogReplicator_Redo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "OraProtoBuf.proto",
}
